import { Bike, Camera, Headphones, Home, Laptop, Shirt, Smartphone } from "lucide-react";
import type { Category, Product, ProductQuery, Seller } from "@/types";

const img = (id: string): string =>
    `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=80`;

export const categories: Category[] = [
    { id: "phone", label: "Điện thoại", icon: Smartphone },
    { id: "laptop", label: "Laptop", icon: Laptop },
    { id: "audio", label: "Âm thanh", icon: Headphones },
    { id: "camera", label: "Máy ảnh", icon: Camera },
    { id: "fashion", label: "Thời trang", icon: Shirt },
    { id: "home", label: "Nhà cửa", icon: Home },
    { id: "bike", label: "Xe đạp", icon: Bike },
];

export const sellers: Record<string, Seller> = {
    linh: { id: "s1", name: "Linh Store", rating: 4.9, totalSales: 1280, responseTime: "Trả lời trong 5 phút", verified: true },
    minh: { id: "s2", name: "Minh Tech", rating: 4.7, totalSales: 642, responseTime: "Trả lời trong 15 phút", verified: true },
    hoa: { id: "s3", name: "Hoa Vintage", rating: 4.8, totalSales: 311, responseTime: "Trả lời trong 1 giờ", verified: false },
    nam: { id: "s4", name: "Nam Cycle", rating: 4.6, totalSales: 98, responseTime: "Trả lời trong 3 giờ", verified: false },
};

export const products: Product[] = [
    {
        id: "p1",
        title: "Tai nghe over-ear chống ồn chủ động",
        description: "Tai nghe không dây, pin 30 giờ, chống ồn chủ động. Đầy đủ hộp, cáp sạc và túi đựng.",
        price: 1850000,
        originalPrice: 3200000,
        images: [img("photo-1505740420928-5e560c06d30e")],
        category: "audio",
        condition: "like-new",
        location: "Quận 1, TP.HCM",
        stock: 1,
        tags: ["bluetooth", "chống ồn"],
        colors: ["Đen", "Bạc"],
        postedLabel: "2 giờ trước",
        createdAt: "2026-10-06T08:00:00Z",
        seller: sellers.minh,
    },
    {
        id: "p2",
        title: "Đồng hồ cơ dây da phong cách tối giản",
        description: "Đồng hồ automatic mặt trắng, dây da nâu, chạy chuẩn, bảo hành shop 3 tháng.",
        price: 2400000,
        images: [img("photo-1523275335684-37898b6baf30")],
        category: "fashion",
        condition: "new",
        location: "Hoàn Kiếm, Hà Nội",
        stock: 3,
        tags: ["automatic", "dây da"],
        colors: ["Nâu"],
        postedLabel: "3 giờ trước",
        createdAt: "2026-10-06T07:00:00Z",
        seller: sellers.linh,
    },
    {
        id: "p3",
        title: "Giày sneaker đỏ size 42",
        description: "Giày mang vài lần, đế còn mới, đã vệ sinh sạch. Có hộp gốc.",
        price: 950000,
        originalPrice: 2100000,
        images: [img("photo-1542291026-7eec264c27ff")],
        category: "fashion",
        condition: "like-new",
        location: "Hải Châu, Đà Nẵng",
        stock: 1,
        tags: ["sneaker", "size 42"],
        colors: ["Đỏ"],
        postedLabel: "5 giờ trước",
        createdAt: "2026-10-06T05:00:00Z",
        seller: sellers.hoa,
    },
    {
        id: "p4",
        title: "Máy ảnh film compact kèm ống kính 50mm",
        description: "Máy ảnh film hoạt động tốt, kèm dây đeo và bao da. Phù hợp người mới chơi film.",
        price: 3600000,
        images: [img("photo-1526170375885-4d8ecf77b99f")],
        category: "camera",
        condition: "well-used",
        location: "Quận 3, TP.HCM",
        stock: 1,
        tags: ["film", "vintage"],
        colors: ["Đen"],
        postedLabel: "Hôm qua",
        createdAt: "2026-10-05T10:00:00Z",
        seller: sellers.minh,
    },
    {
        id: "p5",
        title: "Laptop 13 inch mỏng nhẹ, RAM 16GB",
        description: "Pin còn tốt, máy nguyên zin, không trầy xước đáng kể. Tặng kèm balo và chuột.",
        price: 14500000,
        originalPrice: 22000000,
        images: [img("photo-1517336714731-489689fd1ca8")],
        category: "laptop",
        condition: "like-new",
        location: "Cầu Giấy, Hà Nội",
        stock: 2,
        tags: ["16GB", "SSD 512GB"],
        colors: ["Bạc", "Xám"],
        postedLabel: "Hôm qua",
        createdAt: "2026-10-05T08:00:00Z",
        seller: sellers.linh,
    },
    {
        id: "p6",
        title: "Điện thoại thông minh 128GB, fullbox",
        description: "Máy chính hãng, pin 92%, màn hình không xước. Fullbox, bảo hành 1 tháng.",
        price: 6800000,
        originalPrice: 11900000,
        images: [img("photo-1511707171634-5f897ff02aa9")],
        category: "phone",
        condition: "like-new",
        location: "Thủ Đức, TP.HCM",
        stock: 4,
        tags: ["128GB", "fullbox"],
        colors: ["Đen", "Trắng", "Xanh"],
        postedLabel: "2 ngày trước",
        createdAt: "2026-10-04T09:00:00Z",
        seller: sellers.minh,
    },
    {
        id: "p7",
        title: "Sofa vải 2 chỗ màu xám",
        description: "Sofa gọn nhẹ, vải bọc dễ giặt, khung gỗ chắc chắn. Người mua tự vận chuyển hoặc thoả thuận ship.",
        price: 2900000,
        images: [img("photo-1555041469-a586c61ea9bc")],
        category: "home",
        condition: "well-used",
        location: "Bình Thạnh, TP.HCM",
        stock: 1,
        tags: ["sofa", "phòng khách"],
        colors: ["Xám"],
        postedLabel: "2 ngày trước",
        createdAt: "2026-10-04T06:00:00Z",
        seller: sellers.hoa,
    },
    {
        id: "p8",
        title: "Xe đạp thành phố khung nhôm",
        description: "Xe đạp 7 tốc độ, phanh đĩa, đã thay lốp mới. Chạy êm, phù hợp đi làm hằng ngày.",
        price: 4200000,
        originalPrice: 5900000,
        images: [img("photo-1485965120184-e220f721d03e")],
        category: "bike",
        condition: "like-new",
        location: "Ninh Kiều, Cần Thơ",
        stock: 1,
        tags: ["7 tốc độ", "phanh đĩa"],
        colors: ["Xanh navy"],
        postedLabel: "3 ngày trước",
        createdAt: "2026-10-03T09:00:00Z",
        seller: sellers.nam,
    },
    {
        id: "p9",
        title: "Balo du lịch chống nước 25L",
        description: "Balo còn rất mới, nhiều ngăn, có ngăn laptop 15 inch. Chưa qua sử dụng.",
        price: 420000,
        originalPrice: 650000,
        images: [img("photo-1553062407-98eeb64c6a62")],
        category: "fashion",
        condition: "new",
        location: "Quận 7, TP.HCM",
        stock: 6,
        tags: ["chống nước", "25L"],
        colors: ["Đen", "Be"],
        postedLabel: "3 ngày trước",
        createdAt: "2026-10-03T07:00:00Z",
        seller: sellers.linh,
    },
    {
        id: "p10",
        title: "Kính mát gọng nhựa phân cực",
        description: "Kính chống tia UV400, tròng phân cực, kèm hộp và khăn lau.",
        price: 380000,
        images: [img("photo-1572635196237-14b3f281503f")],
        category: "fashion",
        condition: "new",
        location: "Hoàn Kiếm, Hà Nội",
        stock: 8,
        tags: ["UV400", "phân cực"],
        colors: ["Đen"],
        postedLabel: "4 ngày trước",
        createdAt: "2026-10-02T09:00:00Z",
        seller: sellers.hoa,
    },
    {
        id: "p11",
        title: "Laptop văn phòng 15 inch cũ giá rẻ",
        description: "Máy chạy ổn định cho học tập, văn phòng. Pin dùng được khoảng 3 giờ, có vài vết xước nhỏ.",
        price: 5200000,
        images: [img("photo-1496181133206-80ce9b88a853")],
        category: "laptop",
        condition: "well-used",
        location: "Hải Châu, Đà Nẵng",
        stock: 2,
        tags: ["văn phòng", "SSD"],
        colors: ["Xám"],
        postedLabel: "5 ngày trước",
        createdAt: "2026-10-01T09:00:00Z",
        seller: sellers.minh,
    },
];

export function getProducts({ category, sort = "newest" }: ProductQuery = {}): Product[] {
    const filtered = category ? products.filter((p) => p.category === category) : [...products];

    return filtered.sort((a, b) => {
        if (sort === "price-asc") return a.price - b.price;
        if (sort === "price-desc") return b.price - a.price;
        return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
    });
}